### ISSUE TITLE
Undefined component in Usage section of README.md

### ISSUE THREAD

**Issue by sugar-syrup** [jowillianto/ngl-viewer#4]
I tried replicating what was given in the Usage section in README.md and it throws the following errors
```
1 import ProteinViewer, {ProteinStage} from "@jowillianto/ngl-viewer/dist"
                         ~~~~~~~~~~~~

src/App.tsx:1:24 - error TS6133: 'ProteinStage' is declared but its value is never read.

1 import ProteinViewer, {ProteinStage} from "@jowillianto/ngl-viewer/dist"
                         ~~~~~~~~~~~~

src/App.tsx:20:8 - error TS2304: Cannot find name 'ViewerStage'.

20       <ViewerStage height = "800px" width = "800px" />
          ~~~~~~~~~~~
```

**Comment by jowillianto** [comment]
I must have forgotten to update the README for a very long time. I have updated the README. Could you please check it out ?

**Comment by sugar-syrup** [comment]
There still is this one issue. I am not sure if I am missing something
```
src/App.tsx:20:20 - error TS2322: Type '{ height: string; width: string; }' is not assignable to type 'IntrinsicAttributes & NGLStageProps'.
  Property 'height' does not exist on type 'IntrinsicAttributes & NGLStageProps'.

20       <ViewerStage height = "800px" width = "800px" />
                      ~~~~~~```

**Comment by jowillianto** [comment]
Can you try removing the following ? I will update the README accordingly later
```
{
  <ViewerStage  containerStyles = {{
    height : "800px", width : "800px"
  }}/>
}
```

**Comment by sugar-syrup** [comment]
The build worked without any issues. However, the component is not visible, and I can only see a black rectangle. 
![image](https://github.com/user-attachments/assets/f868c402-b725-4ac9-bbb7-7ff962eec2dc)

**Comment by jowillianto** [comment]
Try taking a look at the develop branch in src/App.tsx
I have always used that file to test.

**Comment by sugar-syrup** [comment]
Yes, that works! Thank you!
